// Mapeamento de keywords em Portugues Brasileiro para emojis
// Permite busca em PT-BR no emoji picker

// Tipo do mapeamento
type EmojiKeywordsMap = Record<string, string[]>;

// Keywords em Portugues para emojis mais usados
// Chave: ID do emoji no emoji-mart
// Valor: Array de termos de busca em PT-BR
const EMOJI_KEYWORDS_PT: EmojiKeywordsMap = {
  // ========================================
  // Rostos Felizes e Sorrisos
  // ========================================
  grinning: ['feliz', 'sorriso', 'alegre', 'contente', 'sorrindo'],
  smiley: ['feliz', 'sorriso', 'alegre', 'contente'],
  smile: ['feliz', 'sorriso', 'alegre', 'olhos'],
  grin: ['feliz', 'sorriso', 'alegre', 'dentes'],
  laughing: ['rindo', 'risada', 'gargalhada', 'feliz'],
  sweat_smile: ['suor', 'nervoso', 'aliviado', 'sorriso'],
  rofl: ['rolando', 'rindo', 'muito', 'engraçado', 'hilário'],
  joy: ['chorando', 'rindo', 'lágrimas', 'alegria', 'feliz'],
  slightly_smiling_face: ['sorriso', 'leve', 'feliz'],
  upside_down_face: ['invertido', 'brincadeira', 'sarcasmo'],
  wink: ['piscada', 'piscando', 'flerte'],
  blush: ['corado', 'envergonhado', 'tímido', 'feliz'],
  innocent: ['anjo', 'inocente', 'aureola', 'santo'],

  // ========================================
  // Rostos Afetuosos
  // ========================================
  smiling_face_with_three_hearts: ['amor', 'apaixonado', 'corações', 'carinho'],
  heart_eyes: ['amor', 'apaixonado', 'olhos', 'coração'],
  star_struck: ['estrelas', 'impressionado', 'incrível', 'uau'],
  kissing_heart: ['beijo', 'amor', 'coração', 'carinho'],
  kissing: ['beijo', 'beijando'],
  relaxed: ['relaxado', 'tranquilo', 'calmo'],
  kissing_closed_eyes: ['beijo', 'olhos', 'fechados'],
  kissing_smiling_eyes: ['beijo', 'sorrindo', 'feliz'],
  smiling_face_with_tear: ['sorriso', 'lágrima', 'emocionado'],

  // ========================================
  // Rostos com Língua
  // ========================================
  yum: ['delícia', 'gostoso', 'comida', 'língua'],
  stuck_out_tongue: ['língua', 'brincadeira', 'zoeira'],
  stuck_out_tongue_winking_eye: ['língua', 'piscando', 'brincadeira'],
  stuck_out_tongue_closed_eyes: ['língua', 'fechados', 'brincadeira'],
  zany_face: ['louco', 'maluco', 'doido', 'zueiro'],
  face_with_raised_eyebrow: ['sobrancelha', 'desconfiado', 'suspeito'],
  monocle_face: ['monóculo', 'analisando', 'investigando'],

  // ========================================
  // Rostos com Mãos
  // ========================================
  hugs: ['abraço', 'abraçando', 'carinho', 'amor'],
  hand_over_mouth: ['mão', 'boca', 'ops', 'surpreso'],
  shushing_face: ['silêncio', 'quieto', 'segredo', 'shh'],
  thinking: ['pensando', 'pensativo', 'hmm', 'dúvida'],

  // ========================================
  // Rostos Neutros e Céticos
  // ========================================
  neutral_face: ['neutro', 'sem expressão', 'indiferente'],
  expressionless: ['sem expressão', 'entediado', 'neutro'],
  no_mouth: ['sem boca', 'silêncio', 'mudo'],
  smirk: ['sorriso', 'malicioso', 'convencido'],
  unamused: ['entediado', 'irritado', 'chateado'],
  roll_eyes: ['revirar olhos', 'entediado', 'descrente'],
  grimacing: ['constrangido', 'nervoso', 'estranho'],
  lying_face: ['mentindo', 'mentira', 'pinóquio'],

  // ========================================
  // Rostos Sonolentos
  // ========================================
  relieved: ['aliviado', 'relaxado', 'tranquilo'],
  pensive: ['pensativo', 'triste', 'melancólico'],
  sleepy: ['sonolento', 'sono', 'cansado'],
  drooling_face: ['babando', 'delícia', 'faminto'],
  sleeping: ['dormindo', 'sono', 'zzz'],

  // ========================================
  // Rostos Doentes
  // ========================================
  mask: ['máscara', 'doente', 'covid', 'gripe'],
  face_with_thermometer: ['termômetro', 'febre', 'doente'],
  face_with_head_bandage: ['machucado', 'ferido', 'bandagem'],
  nauseated_face: ['enjoado', 'nojo', 'vômito'],
  vomiting_face: ['vomitando', 'vômito', 'enjoado'],
  sneezing_face: ['espirrando', 'espirro', 'alergia'],
  hot_face: ['quente', 'calor', 'suando'],
  cold_face: ['frio', 'gelado', 'congelando'],
  woozy_face: ['tonto', 'bêbado', 'zonzo'],
  dizzy_face: ['tonto', 'desmaiando', 'zonzo'],
  exploding_head: ['cabeça', 'explodindo', 'chocado', 'mente'],

  // ========================================
  // Rostos Negativos
  // ========================================
  frowning: ['triste', 'chateado', 'desapontado'],
  anguished: ['angustiado', 'preocupado', 'aflito'],
  fearful: ['medo', 'assustado', 'apavorado'],
  cold_sweat: ['suor', 'frio', 'nervoso', 'medo'],
  disappointed_relieved: ['aliviado', 'decepcionado', 'suor'],
  cry: ['chorando', 'triste', 'lágrima'],
  sob: ['chorando', 'muito', 'triste', 'lágrimas'],
  scream: ['gritando', 'medo', 'terror', 'assustado'],
  confounded: ['confuso', 'frustrado', 'irritado'],
  persevere: ['perseverando', 'sofrendo', 'aguentando'],
  disappointed: ['desapontado', 'triste', 'decepcionado'],
  sweat: ['suor', 'preocupado', 'nervoso'],
  weary: ['cansado', 'exausto', 'esgotado'],
  tired_face: ['cansado', 'exausto', 'esgotado'],

  // ========================================
  // Rostos com Raiva
  // ========================================
  triumph: ['triunfo', 'bufando', 'determinado'],
  pout: ['bravo', 'raiva', 'irritado', 'vermelho'],
  angry: ['bravo', 'raiva', 'irritado'],
  rage: ['raiva', 'fúria', 'muito bravo', 'vermelho'],
  cursing_face: ['xingando', 'palavrão', 'bravo'],
  smiling_imp: ['diabinho', 'travesso', 'malvado'],
  imp: ['diabo', 'demônio', 'malvado'],
  skull: ['caveira', 'crânio', 'morte', 'morto'],
  skull_and_crossbones: ['caveira', 'ossos', 'perigo', 'morte'],

  // ========================================
  // Gestos e Partes do Corpo
  // ========================================
  wave: ['acenando', 'tchau', 'oi', 'mão'],
  raised_back_of_hand: ['mão', 'costas', 'levantada'],
  raised_hand_with_fingers_splayed: ['mão', 'aberta', 'pare'],
  hand: ['mão', 'pare', 'oi'],
  vulcan_salute: ['vulcano', 'spock', 'star trek'],
  ok_hand: ['ok', 'beleza', 'perfeito', 'mão'],
  pinched_fingers: ['italiano', 'que', 'dedos'],
  pinching_hand: ['pequeno', 'pouco', 'pitada'],
  v: ['vitória', 'paz', 'dois', 'dedos'],
  crossed_fingers: ['dedos', 'cruzados', 'sorte'],
  love_you_gesture: ['amor', 'rock', 'mão'],
  metal: ['metal', 'rock', 'chifres'],
  call_me_hand: ['liga', 'telefone', 'mão'],
  point_left: ['apontando', 'esquerda', 'dedo'],
  point_right: ['apontando', 'direita', 'dedo'],
  point_up_2: ['apontando', 'cima', 'dedo'],
  middle_finger: ['dedo', 'meio', 'ofensa'],
  point_down: ['apontando', 'baixo', 'dedo'],
  point_up: ['apontando', 'cima', 'dedo'],
  '+1': ['positivo', 'legal', 'curtir', 'joinha', 'like'],
  thumbsup: ['positivo', 'legal', 'curtir', 'joinha', 'like'],
  '-1': ['negativo', 'ruim', 'não curtir'],
  thumbsdown: ['negativo', 'ruim', 'não curtir'],
  fist_raised: ['punho', 'força', 'levantado'],
  fist_oncoming: ['soco', 'punho', 'batendo'],
  fist_left: ['punho', 'esquerda', 'soco'],
  fist_right: ['punho', 'direita', 'soco'],
  clap: ['palmas', 'aplausos', 'batendo'],
  raised_hands: ['mãos', 'levantadas', 'celebração', 'aleluia'],
  open_hands: ['mãos', 'abertas', 'jazz'],
  palms_up_together: ['mãos', 'juntas', 'pedindo'],
  handshake: ['aperto', 'mãos', 'acordo', 'negócio'],
  pray: ['oração', 'rezando', 'mãos juntas', 'por favor', 'obrigado'],
  writing_hand: ['escrevendo', 'mão', 'caneta'],
  nail_care: ['unha', 'esmalte', 'manicure'],
  selfie: ['selfie', 'foto', 'celular'],
  muscle: ['músculo', 'forte', 'força', 'braço'],
  mechanical_arm: ['braço', 'mecânico', 'robô'],
  leg: ['perna'],
  mechanical_leg: ['perna', 'mecânica', 'robô'],
  foot: ['pé'],
  ear: ['orelha', 'ouvido'],
  ear_with_hearing_aid: ['orelha', 'aparelho', 'auditivo'],
  nose: ['nariz'],
  brain: ['cérebro', 'mente', 'pensar'],
  tooth: ['dente'],
  bone: ['osso'],
  eyes: ['olhos', 'olhando'],
  eye: ['olho'],
  tongue: ['língua'],
  lips: ['lábios', 'boca', 'beijo'],

  // ========================================
  // Corações e Amor
  // ========================================
  heart: ['coração', 'amor', 'vermelho'],
  orange_heart: ['coração', 'laranja', 'amor'],
  yellow_heart: ['coração', 'amarelo', 'amor', 'amizade'],
  green_heart: ['coração', 'verde', 'amor'],
  blue_heart: ['coração', 'azul', 'amor'],
  purple_heart: ['coração', 'roxo', 'amor'],
  black_heart: ['coração', 'preto', 'escuro'],
  brown_heart: ['coração', 'marrom', 'amor'],
  white_heart: ['coração', 'branco', 'amor'],
  broken_heart: ['coração', 'partido', 'triste', 'dor'],
  two_hearts: ['corações', 'dois', 'amor'],
  revolving_hearts: ['corações', 'girando', 'amor'],
  heartbeat: ['coração', 'batendo', 'pulsando'],
  heartpulse: ['coração', 'pulsando', 'batendo'],
  sparkling_heart: ['coração', 'brilhando', 'amor'],
  cupid: ['cupido', 'flecha', 'amor', 'coração'],
  gift_heart: ['presente', 'coração', 'amor'],
  heart_decoration: ['coração', 'decoração', 'amor'],
  peace_symbol: ['paz', 'símbolo'],
  latin_cross: ['cruz', 'religião', 'cristão'],
  star_of_david: ['estrela', 'davi', 'judaísmo'],
  infinity: ['infinito', 'eterno', 'para sempre'],

  // ========================================
  // Animais
  // ========================================
  dog: ['cachorro', 'cão', 'animal', 'pet'],
  cat: ['gato', 'felino', 'animal', 'pet'],
  mouse: ['rato', 'camundongo', 'animal'],
  hamster: ['hamster', 'roedor', 'animal', 'pet'],
  rabbit: ['coelho', 'animal'],
  fox_face: ['raposa', 'animal'],
  bear: ['urso', 'animal'],
  panda_face: ['panda', 'urso', 'animal'],
  koala: ['coala', 'animal'],
  tiger: ['tigre', 'felino', 'animal'],
  lion: ['leão', 'felino', 'animal', 'rei'],
  cow: ['vaca', 'animal', 'fazenda'],
  pig: ['porco', 'animal', 'fazenda'],
  frog: ['sapo', 'animal'],
  monkey_face: ['macaco', 'animal'],
  see_no_evil: ['macaco', 'olhos', 'não ver'],
  hear_no_evil: ['macaco', 'orelhas', 'não ouvir'],
  speak_no_evil: ['macaco', 'boca', 'não falar'],
  monkey: ['macaco', 'animal'],
  chicken: ['galinha', 'frango', 'animal'],
  penguin: ['pinguim', 'animal'],
  bird: ['pássaro', 'ave', 'animal'],
  baby_chick: ['pintinho', 'filhote', 'animal'],
  hatching_chick: ['pintinho', 'nascendo', 'ovo'],
  hatched_chick: ['pintinho', 'nasceu', 'filhote'],
  duck: ['pato', 'ave', 'animal'],
  eagle: ['águia', 'ave', 'animal'],
  owl: ['coruja', 'ave', 'animal'],
  bat: ['morcego', 'animal'],
  wolf: ['lobo', 'animal'],
  boar: ['javali', 'animal'],
  horse: ['cavalo', 'animal'],
  unicorn: ['unicórnio', 'mágico', 'animal'],
  bee: ['abelha', 'inseto'],
  bug: ['inseto', 'bicho'],
  butterfly: ['borboleta', 'inseto'],
  snail: ['caracol', 'animal'],
  lady_beetle: ['joaninha', 'inseto'],
  ant: ['formiga', 'inseto'],
  mosquito: ['mosquito', 'inseto', 'pernilongo'],
  cricket: ['grilo', 'inseto'],
  spider: ['aranha', 'inseto'],
  spider_web: ['teia', 'aranha'],
  scorpion: ['escorpião', 'animal'],
  turtle: ['tartaruga', 'animal'],
  snake: ['cobra', 'serpente', 'animal'],
  lizard: ['lagarto', 'animal'],
  t_rex: ['dinossauro', 'tiranossauro', 'animal'],
  sauropod: ['dinossauro', 'animal'],
  octopus: ['polvo', 'animal', 'mar'],
  squid: ['lula', 'animal', 'mar'],
  shrimp: ['camarão', 'animal', 'mar'],
  lobster: ['lagosta', 'animal', 'mar'],
  crab: ['caranguejo', 'animal', 'mar'],
  blowfish: ['baiacu', 'peixe', 'animal'],
  tropical_fish: ['peixe', 'tropical', 'animal'],
  fish: ['peixe', 'animal'],
  dolphin: ['golfinho', 'animal', 'mar'],
  whale: ['baleia', 'animal', 'mar'],
  whale2: ['baleia', 'animal', 'mar'],
  shark: ['tubarão', 'animal', 'mar'],
  crocodile: ['crocodilo', 'jacaré', 'animal'],
  leopard: ['leopardo', 'onça', 'animal'],
  zebra: ['zebra', 'animal'],
  gorilla: ['gorila', 'animal'],
  orangutan: ['orangotango', 'animal'],
  elephant: ['elefante', 'animal'],
  mammoth: ['mamute', 'animal'],
  rhinoceros: ['rinoceronte', 'animal'],
  hippopotamus: ['hipopótamo', 'animal'],
  camel: ['camelo', 'animal'],
  giraffe: ['girafa', 'animal'],
  kangaroo: ['canguru', 'animal'],
  water_buffalo: ['búfalo', 'animal'],
  ox: ['boi', 'animal'],
  ram: ['carneiro', 'animal'],
  sheep: ['ovelha', 'animal'],
  goat: ['cabra', 'bode', 'animal'],
  deer: ['cervo', 'veado', 'animal'],
  llama: ['lhama', 'animal'],
  sloth: ['preguiça', 'animal'],
  otter: ['lontra', 'animal'],
  skunk: ['gambá', 'animal'],
  badger: ['texugo', 'animal'],
  raccoon: ['guaxinim', 'animal'],
  parrot: ['papagaio', 'ave', 'animal'],
  swan: ['cisne', 'ave', 'animal'],
  flamingo: ['flamingo', 'ave', 'animal'],
  peacock: ['pavão', 'ave', 'animal'],
  dodo: ['dodô', 'ave', 'animal'],
  seal: ['foca', 'animal', 'mar'],
  guide_dog: ['cachorro', 'guia', 'cego'],
  dog2: ['cachorro', 'cão', 'animal'],
  poodle: ['poodle', 'cachorro', 'animal'],
  cat2: ['gato', 'animal'],
  black_cat: ['gato', 'preto', 'animal'],
  rooster: ['galo', 'ave', 'animal'],
  turkey: ['peru', 'ave', 'animal'],
  dove: ['pomba', 'paz', 'ave'],
  rabbit2: ['coelho', 'animal'],
  mouse2: ['rato', 'camundongo', 'animal'],
  rat: ['rato', 'animal'],
  chipmunk: ['esquilo', 'animal'],
  hedgehog: ['porco-espinho', 'animal'],
  feet: ['patas', 'pegadas', 'animal'],
  dragon: ['dragão', 'animal', 'mito'],
  dragon_face: ['dragão', 'animal', 'mito'],

  // ========================================
  // Comidas e Bebidas
  // ========================================
  apple: ['maçã', 'fruta', 'vermelha'],
  green_apple: ['maçã', 'verde', 'fruta'],
  pear: ['pera', 'fruta'],
  tangerine: ['tangerina', 'laranja', 'fruta'],
  lemon: ['limão', 'fruta', 'amarelo'],
  banana: ['banana', 'fruta'],
  watermelon: ['melancia', 'fruta'],
  grapes: ['uvas', 'fruta'],
  strawberry: ['morango', 'fruta'],
  melon: ['melão', 'fruta'],
  cherries: ['cerejas', 'fruta'],
  peach: ['pêssego', 'fruta'],
  mango: ['manga', 'fruta'],
  pineapple: ['abacaxi', 'fruta'],
  coconut: ['coco', 'fruta'],
  kiwi_fruit: ['kiwi', 'fruta'],
  tomato: ['tomate', 'legume'],
  eggplant: ['berinjela', 'legume'],
  avocado: ['abacate', 'fruta'],
  broccoli: ['brócolis', 'legume', 'verde'],
  leafy_green: ['folha', 'verde', 'alface'],
  cucumber: ['pepino', 'legume'],
  hot_pepper: ['pimenta', 'picante'],
  corn: ['milho', 'legume'],
  carrot: ['cenoura', 'legume'],
  garlic: ['alho', 'tempero'],
  onion: ['cebola', 'legume'],
  potato: ['batata', 'legume'],
  sweet_potato: ['batata', 'doce', 'legume'],
  croissant: ['croissant', 'pão', 'francês'],
  baguette_bread: ['baguete', 'pão', 'francês'],
  pretzel: ['pretzel', 'pão', 'alemão'],
  bagel: ['bagel', 'pão', 'rosca'],
  pancakes: ['panquecas', 'café', 'manhã'],
  waffle: ['waffle', 'café', 'manhã'],
  cheese: ['queijo', 'laticínio'],
  meat_on_bone: ['carne', 'osso', 'churrasco'],
  poultry_leg: ['frango', 'coxa', 'carne'],
  cut_of_meat: ['carne', 'bife', 'filé'],
  bacon: ['bacon', 'carne', 'porco'],
  hamburger: ['hambúrguer', 'lanche', 'comida'],
  fries: ['batata', 'frita', 'lanche'],
  pizza: ['pizza', 'italiana', 'comida'],
  hotdog: ['cachorro-quente', 'salsicha', 'lanche'],
  sandwich: ['sanduíche', 'lanche', 'pão'],
  taco: ['taco', 'mexicano', 'comida'],
  burrito: ['burrito', 'mexicano', 'comida'],
  tamale: ['tamale', 'mexicano', 'comida'],
  stuffed_flatbread: ['pão', 'recheado', 'árabe'],
  falafel: ['falafel', 'árabe', 'comida'],
  egg: ['ovo', 'comida'],
  cooking: ['frigideira', 'ovo', 'cozinhando'],
  shallow_pan_of_food: ['panela', 'paella', 'comida'],
  stew: ['ensopado', 'panela', 'comida'],
  fondue: ['fondue', 'queijo', 'comida'],
  bowl_with_spoon: ['tigela', 'colher', 'comida'],
  salad: ['salada', 'verde', 'saudável'],
  popcorn: ['pipoca', 'cinema', 'lanche'],
  butter: ['manteiga', 'laticínio'],
  salt: ['sal', 'tempero'],
  canned_food: ['enlatado', 'conserva', 'comida'],
  bento: ['bentô', 'japonês', 'comida'],
  rice_cracker: ['biscoito', 'arroz', 'japonês'],
  rice_ball: ['onigiri', 'arroz', 'japonês'],
  rice: ['arroz', 'comida'],
  curry: ['curry', 'indiano', 'comida'],
  ramen: ['ramen', 'macarrão', 'japonês'],
  spaghetti: ['espaguete', 'macarrão', 'italiano'],
  oden: ['oden', 'japonês', 'comida'],
  sushi: ['sushi', 'japonês', 'comida'],
  fried_shrimp: ['camarão', 'frito', 'tempurá'],
  fish_cake: ['bolinho', 'peixe', 'japonês'],
  moon_cake: ['bolo', 'lua', 'chinês'],
  dango: ['dango', 'japonês', 'doce'],
  dumpling: ['dumpling', 'bolinho', 'chinês'],
  fortune_cookie: ['biscoito', 'sorte', 'chinês'],
  takeout_box: ['marmita', 'chinês', 'comida'],
  oyster: ['ostra', 'frutos do mar'],
  icecream: ['sorvete', 'casquinha', 'doce'],
  shaved_ice: ['raspadinha', 'gelo', 'doce'],
  ice_cream: ['sorvete', 'doce', 'gelado'],
  doughnut: ['donut', 'rosquinha', 'doce'],
  cookie: ['biscoito', 'cookie', 'doce'],
  birthday: ['bolo', 'aniversário', 'festa'],
  cake: ['bolo', 'fatia', 'doce'],
  cupcake: ['cupcake', 'bolinho', 'doce'],
  pie: ['torta', 'doce'],
  chocolate_bar: ['chocolate', 'barra', 'doce'],
  candy: ['bala', 'doce'],
  lollipop: ['pirulito', 'doce'],
  custard: ['pudim', 'doce', 'sobremesa'],
  honey_pot: ['mel', 'pote', 'doce'],
  baby_bottle: ['mamadeira', 'bebê', 'leite'],
  milk_glass: ['leite', 'copo', 'bebida'],
  coffee: ['café', 'xícara', 'bebida'],
  teapot: ['bule', 'chá', 'bebida'],
  tea: ['chá', 'xícara', 'bebida'],
  sake: ['saquê', 'japonês', 'bebida'],
  champagne: ['champanhe', 'espumante', 'bebida'],
  wine_glass: ['vinho', 'taça', 'bebida'],
  cocktail: ['coquetel', 'drink', 'bebida'],
  tropical_drink: ['drink', 'tropical', 'bebida'],
  beer: ['cerveja', 'bebida', 'caneca'],
  beers: ['cervejas', 'brinde', 'bebida'],
  clinking_glasses: ['brinde', 'taças', 'bebida'],
  tumbler_glass: ['copo', 'whisky', 'bebida'],
  cup_with_straw: ['copo', 'canudo', 'refrigerante'],
  bubble_tea: ['bubble tea', 'chá', 'pérolas'],
  beverage_box: ['suco', 'caixinha', 'bebida'],
  mate: ['chimarrão', 'cuia', 'bebida'],
  ice_cube: ['gelo', 'cubo', 'gelado'],
  chopsticks: ['hashis', 'pauzinhos', 'japonês'],
  plate_with_cutlery: ['prato', 'talheres', 'comida'],
  fork_and_knife: ['garfo', 'faca', 'talheres'],
  spoon: ['colher', 'talher'],
  hocho: ['faca', 'cozinha', 'chef'],
  amphora: ['ânfora', 'vaso', 'antigo'],

  // ========================================
  // Atividades e Esportes
  // ========================================
  soccer: ['futebol', 'bola', 'esporte'],
  basketball: ['basquete', 'bola', 'esporte'],
  football: ['futebol americano', 'bola', 'esporte'],
  baseball: ['beisebol', 'bola', 'esporte'],
  softball: ['softball', 'bola', 'esporte'],
  tennis: ['tênis', 'bola', 'esporte'],
  volleyball: ['vôlei', 'bola', 'esporte'],
  rugby_football: ['rugby', 'bola', 'esporte'],
  flying_disc: ['frisbee', 'disco', 'esporte'],
  '8ball': ['bilhar', 'sinuca', 'bola'],
  ping_pong: ['pingue-pongue', 'tênis de mesa', 'esporte'],
  badminton: ['badminton', 'peteca', 'esporte'],
  boxing_glove: ['boxe', 'luva', 'esporte'],
  martial_arts_uniform: ['artes marciais', 'karatê', 'esporte'],
  goal_net: ['gol', 'rede', 'esporte'],
  golf: ['golfe', 'esporte'],
  ice_skate: ['patinação', 'gelo', 'esporte'],
  fishing_pole_and_fish: ['pesca', 'peixe', 'anzol'],
  diving_mask: ['mergulho', 'máscara', 'natação'],
  running_shirt_with_sash: ['corrida', 'camisa', 'esporte'],
  ski: ['esqui', 'neve', 'esporte'],
  sled: ['trenó', 'neve'],
  curling_stone: ['curling', 'gelo', 'esporte'],
  dart: ['dardo', 'alvo', 'esporte'],
  yo_yo: ['ioiô', 'brinquedo'],
  kite: ['pipa', 'papagaio', 'brinquedo'],
  swimming: ['natação', 'nadando', 'esporte'],
  surfing: ['surfe', 'surfando', 'esporte'],
  rowing: ['remo', 'remando', 'esporte'],
  climbing: ['escalada', 'escalando', 'esporte'],
  biking: ['ciclismo', 'bicicleta', 'esporte'],
  mountain_biking: ['mountain bike', 'bicicleta', 'esporte'],
  horse_racing: ['corrida', 'cavalos', 'esporte'],
  trophy: ['troféu', 'vitória', 'campeão'],
  medal_sports: ['medalha', 'esporte', 'prêmio'],
  medal_military: ['medalha', 'militar', 'prêmio'],
  '1st_place_medal': ['medalha', 'ouro', 'primeiro'],
  '2nd_place_medal': ['medalha', 'prata', 'segundo'],
  '3rd_place_medal': ['medalha', 'bronze', 'terceiro'],
  reminder_ribbon: ['fita', 'lembrete', 'prêmio'],
  rosette: ['roseta', 'prêmio', 'vitória'],
  ticket: ['ingresso', 'bilhete', 'entrada'],
  tickets: ['ingressos', 'bilhetes', 'entradas'],
  performing_arts: ['teatro', 'máscaras', 'arte'],
  art: ['arte', 'pintura', 'quadro'],
  clapper: ['claquete', 'cinema', 'filme'],
  microphone: ['microfone', 'música', 'karaokê'],
  headphones: ['fones', 'ouvido', 'música'],
  musical_score: ['partitura', 'música', 'notas'],
  musical_keyboard: ['teclado', 'piano', 'música'],
  drum: ['bateria', 'tambor', 'música'],
  saxophone: ['saxofone', 'música', 'jazz'],
  trumpet: ['trompete', 'música'],
  guitar: ['violão', 'guitarra', 'música'],
  violin: ['violino', 'música'],
  banjo: ['banjo', 'música'],
  accordion: ['acordeão', 'sanfona', 'música'],
  video_game: ['videogame', 'controle', 'jogar'],
  joystick: ['joystick', 'videogame', 'controle'],
  game_die: ['dado', 'jogo', 'sorte'],
  chess_pawn: ['xadrez', 'peão', 'jogo'],
  jigsaw: ['quebra-cabeça', 'puzzle', 'jogo'],
  teddy_bear: ['ursinho', 'pelúcia', 'brinquedo'],
  nesting_dolls: ['matriosca', 'bonecas', 'russas'],
  balloon: ['balão', 'festa', 'aniversário'],
  confetti_ball: ['confete', 'festa', 'celebração'],
  tada: ['festa', 'celebração', 'parabéns'],
  sparkles: ['brilhos', 'estrelas', 'magia'],

  // ========================================
  // Viagens e Lugares
  // ========================================
  car: ['carro', 'automóvel', 'veículo'],
  taxi: ['táxi', 'carro', 'transporte'],
  blue_car: ['carro', 'azul', 'veículo'],
  bus: ['ônibus', 'transporte'],
  trolleybus: ['ônibus', 'elétrico', 'transporte'],
  racing_car: ['carro', 'corrida', 'fórmula'],
  police_car: ['polícia', 'carro', 'viatura'],
  ambulance: ['ambulância', 'emergência', 'hospital'],
  fire_engine: ['bombeiros', 'caminhão', 'emergência'],
  minibus: ['van', 'microônibus', 'transporte'],
  truck: ['caminhão', 'veículo'],
  articulated_lorry: ['caminhão', 'carreta', 'veículo'],
  tractor: ['trator', 'fazenda', 'veículo'],
  kick_scooter: ['patinete', 'transporte'],
  motorcycle: ['moto', 'motocicleta', 'veículo'],
  bike: ['bicicleta', 'bike', 'transporte'],
  motor_scooter: ['moto', 'scooter', 'transporte'],
  rotating_light: ['sirene', 'emergência', 'polícia'],
  traffic_light: ['semáforo', 'trânsito'],
  vertical_traffic_light: ['semáforo', 'trânsito'],
  stop_sign: ['pare', 'placa', 'trânsito'],
  construction: ['construção', 'obras', 'atenção'],
  anchor: ['âncora', 'barco', 'mar'],
  sailboat: ['barco', 'vela', 'mar'],
  canoe: ['canoa', 'barco', 'água'],
  speedboat: ['lancha', 'barco', 'mar'],
  passenger_ship: ['navio', 'cruzeiro', 'mar'],
  ferry: ['balsa', 'ferry', 'mar'],
  motor_boat: ['barco', 'motor', 'mar'],
  ship: ['navio', 'barco', 'mar'],
  airplane: ['avião', 'voo', 'viagem'],
  small_airplane: ['avião', 'pequeno', 'voo'],
  flight_departure: ['decolagem', 'avião', 'voo'],
  flight_arrival: ['pouso', 'avião', 'voo'],
  parachute: ['paraquedas', 'salto', 'voo'],
  helicopter: ['helicóptero', 'voo'],
  suspension_railway: ['teleférico', 'transporte'],
  mountain_cableway: ['teleférico', 'montanha'],
  aerial_tramway: ['teleférico', 'aéreo'],
  rocket: ['foguete', 'espaço', 'nasa'],
  flying_saucer: ['disco voador', 'ovni', 'alienígena'],
  bellhop_bell: ['campainha', 'hotel', 'recepção'],
  luggage: ['mala', 'bagagem', 'viagem'],
  hourglass: ['ampulheta', 'tempo', 'areia'],
  hourglass_flowing_sand: ['ampulheta', 'tempo', 'passando'],
  watch: ['relógio', 'pulso', 'tempo'],
  alarm_clock: ['despertador', 'alarme', 'tempo'],
  stopwatch: ['cronômetro', 'tempo', 'esporte'],
  timer_clock: ['timer', 'tempo', 'cozinha'],
  mantelpiece_clock: ['relógio', 'antigo', 'tempo'],
  thermometer: ['termômetro', 'temperatura'],
  sun_behind_small_cloud: ['sol', 'nuvem', 'clima'],
  sun_behind_cloud: ['sol', 'nuvem', 'clima'],
  sun_behind_rain_cloud: ['chuva', 'sol', 'clima'],
  cloud_with_rain: ['chuva', 'nuvem', 'clima'],
  cloud_with_snow: ['neve', 'nuvem', 'clima'],
  cloud_with_lightning: ['raio', 'trovão', 'tempestade'],
  cloud_with_lightning_and_rain: ['tempestade', 'raio', 'chuva'],
  snowflake: ['floco', 'neve', 'frio'],
  snowman: ['boneco', 'neve', 'frio'],
  snowman_with_snow: ['boneco', 'neve', 'nevando'],
  comet: ['cometa', 'espaço', 'estrela'],
  fire: ['fogo', 'chama', 'quente'],
  droplet: ['gota', 'água', 'chuva'],
  ocean: ['oceano', 'onda', 'mar'],
  christmas_tree: ['árvore', 'natal', 'festa'],
  fireworks: ['fogos', 'artifício', 'festa'],
  sparkler: ['vela', 'faísca', 'festa'],
  firecracker: ['foguete', 'explosivo', 'festa'],
  moon: ['lua', 'cheia', 'noite'],
  new_moon: ['lua', 'nova', 'noite'],
  first_quarter_moon: ['lua', 'quarto', 'crescente'],
  waxing_gibbous_moon: ['lua', 'crescente', 'noite'],
  full_moon: ['lua', 'cheia', 'noite'],
  waning_gibbous_moon: ['lua', 'minguante', 'noite'],
  last_quarter_moon: ['lua', 'quarto', 'minguante'],
  crescent_moon: ['lua', 'crescente', 'noite'],
  new_moon_with_face: ['lua', 'rosto', 'nova'],
  first_quarter_moon_with_face: ['lua', 'rosto', 'quarto'],
  last_quarter_moon_with_face: ['lua', 'rosto', 'quarto'],
  sun_with_face: ['sol', 'rosto', 'dia'],
  star: ['estrela', 'brilho', 'noite'],
  star2: ['estrela', 'brilhante', 'noite'],
  milky_way: ['via láctea', 'galáxia', 'espaço'],
  cloud: ['nuvem', 'céu', 'clima'],
  partly_sunny: ['parcialmente', 'nublado', 'sol'],
  sun_small_cloud: ['sol', 'nuvem', 'clima'],
  rainbow: ['arco-íris', 'cores', 'céu'],
  umbrella: ['guarda-chuva', 'chuva'],
  zap: ['raio', 'trovão', 'tempestade'],
  beach_umbrella: ['guarda-sol', 'praia', 'verão'],
  house: ['casa', 'lar', 'moradia'],
  house_with_garden: ['casa', 'jardim', 'lar'],
  office: ['escritório', 'prédio', 'trabalho'],
  post_office: ['correios', 'prédio', 'carta'],
  hospital: ['hospital', 'prédio', 'saúde'],
  bank: ['banco', 'prédio', 'dinheiro'],
  hotel: ['hotel', 'prédio', 'viagem'],
  convenience_store: ['loja', 'conveniência', 'mercado'],
  school: ['escola', 'prédio', 'estudo'],
  department_store: ['shopping', 'loja', 'compras'],
  factory: ['fábrica', 'indústria', 'prédio'],
  castle: ['castelo', 'palácio', 'medieval'],
  wedding: ['casamento', 'igreja', 'bodas'],
  tokyo_tower: ['torre', 'tóquio', 'japão'],
  statue_of_liberty: ['estátua', 'liberdade', 'nova york'],
  church: ['igreja', 'capela', 'religião'],
  mosque: ['mesquita', 'islã', 'religião'],
  hindu_temple: ['templo', 'hindu', 'religião'],
  synagogue: ['sinagoga', 'judaísmo', 'religião'],
  kaaba: ['caaba', 'meca', 'islã'],
  shinto_shrine: ['santuário', 'xintoísmo', 'japão'],
  railway_car: ['trem', 'vagão', 'transporte'],
  bullettrain_side: ['trem-bala', 'shinkansen', 'japão'],
  bullettrain_front: ['trem-bala', 'frente', 'rápido'],
  train: ['trem', 'locomotiva', 'transporte'],
  metro: ['metrô', 'trem', 'transporte'],
  light_rail: ['trem', 'leve', 'transporte'],
  station: ['estação', 'trem', 'transporte'],
  tram: ['bonde', 'trem', 'transporte'],
  monorail: ['monotrilho', 'trem', 'transporte'],
  mountain_railway: ['trem', 'montanha', 'transporte'],
  steam_locomotive: ['locomotiva', 'vapor', 'trem'],
  oncoming_bus: ['ônibus', 'vindo', 'transporte'],
  fuelpump: ['posto', 'gasolina', 'combustível'],
  busstop: ['ponto', 'ônibus', 'parada'],

  // ========================================
  // Objetos
  // ========================================
  phone: ['telefone', 'celular', 'ligar'],
  telephone_receiver: ['telefone', 'ligar', 'fone'],
  pager: ['pager', 'bip', 'comunicação'],
  fax: ['fax', 'máquina', 'escritório'],
  battery: ['bateria', 'pilha', 'energia'],
  electric_plug: ['tomada', 'plug', 'energia'],
  computer: ['computador', 'desktop', 'pc'],
  desktop_computer: ['computador', 'desktop', 'pc'],
  printer: ['impressora', 'escritório'],
  keyboard: ['teclado', 'computador'],
  computer_mouse: ['mouse', 'computador'],
  trackball: ['trackball', 'mouse', 'computador'],
  minidisc: ['minidisc', 'disco', 'mídia'],
  floppy_disk: ['disquete', 'disco', 'antigo'],
  cd: ['cd', 'disco', 'música'],
  dvd: ['dvd', 'disco', 'filme'],
  abacus: ['ábaco', 'calculadora', 'matemática'],
  movie_camera: ['câmera', 'filme', 'cinema'],
  film_strip: ['filme', 'rolo', 'cinema'],
  film_projector: ['projetor', 'filme', 'cinema'],
  tv: ['televisão', 'tv', 'tela'],
  camera: ['câmera', 'foto', 'fotografia'],
  camera_flash: ['câmera', 'flash', 'foto'],
  video_camera: ['filmadora', 'vídeo', 'câmera'],
  vhs: ['vhs', 'fita', 'vídeo'],
  mag: ['lupa', 'busca', 'procurar'],
  mag_right: ['lupa', 'busca', 'direita'],
  candle: ['vela', 'luz', 'fogo'],
  bulb: ['lâmpada', 'luz', 'ideia'],
  flashlight: ['lanterna', 'luz'],
  izakaya_lantern: ['lanterna', 'japonesa', 'luz'],
  diya_lamp: ['lamparina', 'luz', 'óleo'],
  notebook_with_decorative_cover: ['caderno', 'decorado'],
  closed_book: ['livro', 'fechado', 'leitura'],
  book: ['livro', 'aberto', 'leitura'],
  green_book: ['livro', 'verde', 'leitura'],
  blue_book: ['livro', 'azul', 'leitura'],
  orange_book: ['livro', 'laranja', 'leitura'],
  books: ['livros', 'biblioteca', 'leitura'],
  notebook: ['caderno', 'anotações'],
  ledger: ['livro-caixa', 'contabilidade'],
  page_with_curl: ['página', 'documento', 'papel'],
  scroll: ['pergaminho', 'antigo', 'papel'],
  page_facing_up: ['página', 'documento', 'papel'],
  newspaper: ['jornal', 'notícia', 'mídia'],
  newspaper_roll: ['jornal', 'enrolado', 'mídia'],
  bookmark_tabs: ['marcadores', 'abas', 'organização'],
  bookmark: ['marcador', 'favorito', 'livro'],
  label: ['etiqueta', 'tag', 'preço'],
  moneybag: ['dinheiro', 'saco', 'rico'],
  coin: ['moeda', 'dinheiro'],
  yen: ['iene', 'dinheiro', 'japão'],
  dollar: ['dólar', 'dinheiro', 'eua'],
  euro: ['euro', 'dinheiro', 'europa'],
  pound: ['libra', 'dinheiro', 'reino unido'],
  money_with_wings: ['dinheiro', 'voando', 'gastando'],
  credit_card: ['cartão', 'crédito', 'pagamento'],
  receipt: ['recibo', 'nota', 'compra'],
  chart: ['gráfico', 'crescimento', 'estatística'],
  email: ['email', 'carta', 'mensagem'],
  envelope: ['envelope', 'carta', 'correio'],
  incoming_envelope: ['envelope', 'chegando', 'carta'],
  envelope_with_arrow: ['envelope', 'enviando', 'carta'],
  outbox_tray: ['caixa', 'saída', 'email'],
  inbox_tray: ['caixa', 'entrada', 'email'],
  mailbox: ['caixa', 'correio', 'carta'],
  mailbox_closed: ['caixa', 'correio', 'fechada'],
  mailbox_with_mail: ['caixa', 'correio', 'carta'],
  mailbox_with_no_mail: ['caixa', 'correio', 'vazia'],
  postbox: ['caixa', 'postal', 'carta'],
  ballot_box: ['urna', 'votação', 'eleição'],
  pencil2: ['lápis', 'escrever', 'desenhar'],
  black_nib: ['caneta', 'tinta', 'escrever'],
  fountain_pen: ['caneta', 'tinteiro', 'escrever'],
  pen: ['caneta', 'esferográfica', 'escrever'],
  paintbrush: ['pincel', 'arte', 'pintar'],
  crayon: ['giz', 'cera', 'colorir'],
  memo: ['memorando', 'nota', 'papel'],
  briefcase: ['maleta', 'trabalho', 'escritório'],
  file_folder: ['pasta', 'arquivo', 'documentos'],
  open_file_folder: ['pasta', 'aberta', 'documentos'],
  card_index_dividers: ['divisórias', 'organização', 'arquivo'],
  date: ['calendário', 'data', 'dia'],
  calendar: ['calendário', 'data', 'mês'],
  spiral_notepad: ['bloco', 'notas', 'espiral'],
  spiral_calendar: ['calendário', 'espiral', 'data'],
  card_index: ['fichário', 'índice', 'arquivo'],
  chart_with_upwards_trend: ['gráfico', 'subindo', 'crescimento'],
  chart_with_downwards_trend: ['gráfico', 'descendo', 'queda'],
  bar_chart: ['gráfico', 'barras', 'estatística'],
  clipboard: ['prancheta', 'lista', 'tarefas'],
  pushpin: ['alfinete', 'marcar', 'lembrete'],
  round_pushpin: ['alfinete', 'redondo', 'localização'],
  paperclip: ['clipe', 'papel', 'anexo'],
  linked_paperclips: ['clipes', 'ligados', 'anexo'],
  straight_ruler: ['régua', 'medida', 'reta'],
  triangular_ruler: ['esquadro', 'triângulo', 'desenho'],
  scissors: ['tesoura', 'cortar', 'artesanato'],
  card_file_box: ['arquivo', 'caixa', 'documentos'],
  file_cabinet: ['arquivo', 'gaveta', 'escritório'],
  wastebasket: ['lixeira', 'lixo', 'descarte'],
  lock: ['cadeado', 'trancado', 'seguro'],
  unlock: ['cadeado', 'aberto', 'destrancado'],
  lock_with_ink_pen: ['cadeado', 'caneta', 'privacidade'],
  closed_lock_with_key: ['cadeado', 'chave', 'segurança'],
  key: ['chave', 'trancar', 'abrir'],
  old_key: ['chave', 'antiga', 'vintage'],
  hammer: ['martelo', 'ferramenta', 'construção'],
  axe: ['machado', 'ferramenta', 'cortar'],
  pick: ['picareta', 'ferramenta', 'mineração'],
  hammer_and_pick: ['martelo', 'picareta', 'ferramentas'],
  hammer_and_wrench: ['martelo', 'chave', 'ferramentas'],
  dagger: ['adaga', 'faca', 'arma'],
  crossed_swords: ['espadas', 'cruzadas', 'batalha'],
  gun: ['pistola', 'arma', 'tiro'],
  boomerang: ['bumerangue', 'arremesso'],
  bow_and_arrow: ['arco', 'flecha', 'arqueiro'],
  shield: ['escudo', 'proteção', 'defesa'],
  carpentry_saw: ['serra', 'madeira', 'ferramenta'],
  wrench: ['chave', 'inglesa', 'ferramenta'],
  screwdriver: ['chave de fenda', 'ferramenta'],
  nut_and_bolt: ['parafuso', 'porca', 'ferramenta'],
  gear: ['engrenagem', 'mecânica', 'configuração'],
  clamp: ['grampo', 'ferramenta', 'apertar'],
  balance_scale: ['balança', 'justiça', 'peso'],
  probing_cane: ['bengala', 'cego', 'acessibilidade'],
  link: ['link', 'corrente', 'elo'],
  chains: ['correntes', 'preso', 'ligação'],
  hook: ['gancho', 'pendurar'],
  toolbox: ['caixa', 'ferramentas'],
  magnet: ['ímã', 'magnético', 'atração'],
  ladder: ['escada', 'subir'],
  alembic: ['alambique', 'química', 'laboratório'],
  test_tube: ['tubo', 'ensaio', 'laboratório'],
  petri_dish: ['placa', 'petri', 'laboratório'],
  dna: ['dna', 'genética', 'ciência'],
  microscope: ['microscópio', 'ciência', 'laboratório'],
  telescope: ['telescópio', 'astronomia', 'espaço'],
  satellite: ['satélite', 'espaço', 'comunicação'],
  syringe: ['seringa', 'vacina', 'médico'],
  drop_of_blood: ['gota', 'sangue', 'doação'],
  pill: ['pílula', 'remédio', 'medicamento'],
  adhesive_bandage: ['band-aid', 'curativo', 'machucado'],
  stethoscope: ['estetoscópio', 'médico', 'coração'],
  door: ['porta', 'entrada', 'casa'],
  elevator: ['elevador', 'subir', 'prédio'],
  mirror: ['espelho', 'reflexo'],
  window: ['janela', 'casa', 'vista'],
  bed: ['cama', 'dormir', 'quarto'],
  couch_and_lamp: ['sofá', 'luminária', 'sala'],
  chair: ['cadeira', 'sentar', 'móvel'],
  toilet: ['vaso', 'sanitário', 'banheiro'],
  plunger: ['desentupidor', 'banheiro'],
  shower: ['chuveiro', 'banho', 'banheiro'],
  bathtub: ['banheira', 'banho'],
  mouse_trap: ['ratoeira', 'rato', 'armadilha'],
  razor: ['gilete', 'barbear', 'navalha'],
  lotion_bottle: ['loção', 'creme', 'hidratante'],
  safety_pin: ['alfinete', 'segurança', 'fralda'],
  broom: ['vassoura', 'limpar', 'casa'],
  basket: ['cesto', 'cesta', 'compras'],
  roll_of_paper: ['papel', 'rolo', 'higiênico'],
  bucket: ['balde', 'água', 'limpeza'],
  soap: ['sabão', 'sabonete', 'limpeza'],
  toothbrush: ['escova', 'dentes', 'higiene'],
  sponge: ['esponja', 'limpeza'],
  fire_extinguisher: ['extintor', 'incêndio', 'segurança'],
  shopping_cart: ['carrinho', 'compras', 'supermercado'],
  smoking: ['cigarro', 'fumar', 'tabaco'],
  coffin: ['caixão', 'morte', 'funeral'],
  headstone: ['lápide', 'túmulo', 'cemitério'],
  funeral_urn: ['urna', 'funeral', 'cinzas'],
  moyai: ['moai', 'estátua', 'ilha de páscoa'],
  placard: ['placa', 'cartaz', 'protesto'],

  // ========================================
  // Símbolos
  // ========================================
  '100': ['cem', 'pontos', 'perfeito', 'nota'],
  '1234': ['números', 'senha', 'código'],
  heart_exclamation: ['coração', 'exclamação', 'amor'],
  anger: ['raiva', 'símbolo', 'bravo'],
  boom: ['explosão', 'colisão', 'impacto'],
  dizzy: ['tontura', 'estrela', 'tonto'],
  sweat_drops: ['gotas', 'suor', 'esforço'],
  dash: ['correndo', 'vento', 'pressa'],
  hole: ['buraco', 'círculo'],
  speech_balloon: ['balão', 'fala', 'conversa'],
  thought_balloon: ['balão', 'pensamento', 'ideia'],
  zzz: ['dormindo', 'sono', 'zzz'],
  white_check_mark: ['verificado', 'ok', 'correto', 'certo'],
  ballot_box_with_check: ['caixa', 'verificado', 'votação'],
  heavy_check_mark: ['verificado', 'correto', 'check'],
  x: ['errado', 'não', 'cancelar'],
  negative_squared_cross_mark: ['errado', 'não', 'cancelar'],
  curly_loop: ['laço', 'loop', 'curva'],
  loop: ['laço', 'duplo', 'repetição'],
  part_alternation_mark: ['alternância', 'parte'],
  eight_spoked_asterisk: ['asterisco', 'oito', 'pontas'],
  eight_pointed_black_star: ['estrela', 'oito', 'pontas'],
  sparkle: ['brilho', 'estrela', 'faísca'],
  copyright: ['copyright', 'direitos', 'autoral'],
  registered: ['registrado', 'marca'],
  tm: ['trademark', 'marca', 'registrada'],
  hash: ['hashtag', 'cerquilha', 'número'],
  asterisk: ['asterisco', 'estrela'],
  zero: ['zero', 'número', '0'],
  one: ['um', 'número', '1'],
  two: ['dois', 'número', '2'],
  three: ['três', 'número', '3'],
  four: ['quatro', 'número', '4'],
  five: ['cinco', 'número', '5'],
  six: ['seis', 'número', '6'],
  seven: ['sete', 'número', '7'],
  eight: ['oito', 'número', '8'],
  nine: ['nove', 'número', '9'],
  keycap_ten: ['dez', 'número', '10'],
  capital_abcd: ['letras', 'maiúsculas', 'abc'],
  abcd: ['letras', 'minúsculas', 'abc'],
  symbols: ['símbolos', 'caracteres'],
  abc: ['letras', 'alfabeto', 'abc'],
  a: ['letra', 'a', 'sangue'],
  ab: ['letras', 'ab', 'sangue'],
  b: ['letra', 'b', 'sangue'],
  cl: ['cl', 'limpar'],
  o2: ['letra', 'o', 'sangue'],
  sos: ['sos', 'socorro', 'emergência'],
  no_entry: ['proibido', 'entrada', 'pare'],
  name_badge: ['crachá', 'nome', 'identificação'],
  no_entry_sign: ['proibido', 'não', 'entrada'],
  anger_symbol: ['raiva', 'símbolo', 'bravo'],
  hotsprings: ['termas', 'quente', 'vapor'],
  no_pedestrians: ['proibido', 'pedestres', 'andar'],
  do_not_litter: ['proibido', 'lixo', 'jogar'],
  no_bicycles: ['proibido', 'bicicletas'],
  non_potable_water: ['água', 'não potável', 'proibido'],
  underage: ['menor', 'idade', 'proibido'],
  no_mobile_phones: ['proibido', 'celular', 'telefone'],
  exclamation: ['exclamação', 'atenção', 'importante'],
  grey_exclamation: ['exclamação', 'cinza', 'atenção'],
  question: ['interrogação', 'pergunta', 'dúvida'],
  grey_question: ['interrogação', 'cinza', 'pergunta'],
  bangbang: ['exclamações', 'dupla', 'importante'],
  interrobang: ['interrobang', 'pergunta', 'exclamação'],
  low_brightness: ['brilho', 'baixo', 'escuro'],
  high_brightness: ['brilho', 'alto', 'claro'],
  trident: ['tridente', 'poseidon', 'mar'],
  fleur_de_lis: ['flor', 'lis', 'símbolo'],
  warning: ['aviso', 'atenção', 'perigo'],
  children_crossing: ['crianças', 'atravessando', 'escola'],
  beginner: ['iniciante', 'novato', 'japão'],
  recycle: ['reciclar', 'reciclagem', 'verde'],
  u6307: ['japonês', 'símbolo'],
  diamond_shape_with_a_dot_inside: ['diamante', 'ponto', 'símbolo'],
  cyclone: ['ciclone', 'furacão', 'redemoinho'],
  foggy: ['neblina', 'névoa', 'cidade'],
  closed_umbrella: ['guarda-chuva', 'fechado'],
  night_with_stars: ['noite', 'estrelas', 'cidade'],
  sunrise_over_mountains: ['nascer', 'sol', 'montanhas'],
  sunrise: ['nascer', 'sol', 'manhã'],
  city_sunset: ['pôr', 'sol', 'cidade'],
  city_sunrise: ['nascer', 'sol', 'cidade'],
  bridge_at_night: ['ponte', 'noite', 'cidade'],
  volcano: ['vulcão', 'erupção', 'montanha'],
  earth_africa: ['terra', 'áfrica', 'europa'],
  earth_americas: ['terra', 'américas', 'mundo'],
  earth_asia: ['terra', 'ásia', 'oceania'],
  globe_with_meridians: ['globo', 'internet', 'mundo'],
  waxing_crescent_moon: ['lua', 'crescente', 'fase'],
  waning_crescent_moon: ['lua', 'minguante', 'fase'],
  full_moon_with_face: ['lua', 'cheia', 'rosto'],
  ringed_planet: ['planeta', 'anel', 'saturno'],
  stars: ['estrelas', 'brilho', 'noite'],
  sun_behind_large_cloud: ['sol', 'nuvem', 'grande'],
  tornado: ['tornado', 'furacão', 'vento'],
  fog: ['neblina', 'névoa', 'cinza'],
  wind_face: ['vento', 'rosto', 'soprando'],
  ghost: ['fantasma', 'espírito', 'halloween'],
  alien: ['alienígena', 'et', 'extraterrestre'],
  robot: ['robô', 'máquina', 'tecnologia'],
  jack_o_lantern: ['abóbora', 'halloween', 'lanterna'],
  clown_face: ['palhaço', 'circo', 'engraçado'],
  ogre: ['ogro', 'monstro', 'demônio'],
  goblin: ['goblin', 'monstro', 'demônio'],
  poop: ['cocô', 'fezes', 'merda'],

  // ========================================
  // Bandeiras (mantidas mesmo com noCountryFlags)
  // ========================================
  checkered_flag: ['bandeira', 'xadrez', 'corrida', 'chegada'],
  triangular_flag_on_post: ['bandeira', 'triângulo', 'golfe'],
  crossed_flags: ['bandeiras', 'cruzadas', 'japão'],
  black_flag: ['bandeira', 'preta'],
  white_flag: ['bandeira', 'branca', 'rendição'],
  rainbow_flag: ['bandeira', 'arco-íris', 'lgbtq', 'gay', 'pride'],
  transgender_flag: ['bandeira', 'trans', 'lgbtq'],
  pirate_flag: ['bandeira', 'pirata', 'caveira'],
  flag_br: ['brasil', 'bandeira', 'brasileiro'],
  flag_us: ['eua', 'estados unidos', 'americana'],
  flag_pt: ['portugal', 'bandeira', 'português'],
};

// ========================================
// Export Default
// ========================================
export default EMOJI_KEYWORDS_PT;
